sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libclang-3.7-dev

script:
  - cargo build --verbose --features clang_3_7
  - cargo test --verbose
