sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - wget http://llvm.org/releases/3.7.0/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar -xf clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - export LIBCLANG=$PWD/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04/lib/libclang.so

script:
  - cargo build --verbose --features clang_3_7
  - cp $LIBCLANG target/debug/deps/libclang.so
  - cargo test --verbose
