sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - wget http://llvm.org/releases/3.6.2/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar -xf clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - export LIBCLANG_PATH=$PWD/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04/lib

script:
  - cargo build --verbose --features clang_3_6
  - cargo test --verbose
