sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y clang-3.7

script:
  - cargo build --verbose --features clang_3_7
  - cargo test --verbose
