[package]

name = "clang"
authors = ["Kyle Mayes <kyle@mayeses.com>"]

version = "0.0.1"

readme = "README.md"
license = "MIT"

description = "Rust bindings and idiomatic wrapper for libclang."

documentation = "https://kylemayes.github.io/clang-rs/clang"
repository = "https://github.com/KyleMayes/clang-rs"

[dependencies]

bitflags = "0.3.3"
lazy_static = "0.1.15"
libc = "0.2.2"

[dependencies.clippy]

version = "0.0.30"
optional = true

[dev-dependencies]

uuid = "0.1.18"
