[package]

name = "clang"
authors = ["Kyle Mayes <kyle@mayeses.com>"]

version = "0.3.1"

readme = "README.md"
license = "MIT"

description = "An idiomatic Rust wrapper for libclang."

documentation = "https://kylemayes.github.io/clang-rs/all/clang"
repository = "https://github.com/KyleMayes/clang-rs"

[features]

clang_3_5 = ["clang-sys/clang_3_5"]
clang_3_6 = ["clang-sys/clang_3_6"]
clang_3_7 = ["clang-sys/clang_3_7"]
clang_3_8 = ["clang-sys/clang_3_8"]

[dependencies]

clang-sys = "0.2.0"
lazy_static = "0.1.15"
libc = "0.2.4"

[dependencies.clippy]

version = "0.0.39"
optional = true

[dev-dependencies]

uuid = "0.1.18"
